### ISSUE TITLE
Why is nginx-proxy being pushed about every hour?

### ISSUE THREAD

**Issue by thewaiterofwaiting** [nginx-proxy/nginx-proxy#1012]
Hi,

I am redeploying nginx-proxy on my development machines when a new version is pushed to the Docker repository. I noticed that today a new version is being pushed every hour, orso. See https://hub.docker.com/r/jwilder/nginx-proxy/builds/.

Why is this?

Cheers!

**Comment by vladwing** [comment]
First of all it's not a good idea to update external software when a new version is up. It might not be compatible with the rest of your stack and it might stop functioning. Ideally you should fix it to a specific version on which you run your tests and then from time to time decide to which version to upgrade - normally the latest, but not necessary. In general you should update to newer versions in two cases: when there is a bug - security or otherwise - in the version you are using, or when you need a feature which is not in your current version.

Updates were probably happening because the author made a series of commits which triggered automatic rebuilds of the docker hub.

**Comment by buchdag** [comment]
This issue isn't relevant anymore, closing.
