### ISSUE TITLE
default server for ssl

### ISSUE THREAD

**Issue by Jas2Ma** [nginx-proxy/nginx-proxy#105]
If there are ssl-servers defined and one is requesting a non defined server, the request will be send to the first ssl server.

I change the nginx.tmpl on my own now, but I think there should be a possibility to set a standard ssl-server like you defined it for http/80?

**Comment by jwilder** [comment]
This might be a issue in that the default SSL server block does not have a `default_server` directive here: https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L142

See https://github.com/jwilder/nginx-proxy#how-ssl-support-works

**Comment by Jas2Ma** [comment]
There is no default SSL server block, like it is for non-ssl. That's because one needs the right certificates for the requested domain.

Maybe there should be one garbage default server per domain registered for use with ssl by env .

**Comment by chschu** [comment]
A fix for this would be really nice, because landing on the wrong virtual host when restarting a container (or using the server's IP address) is really confusing.

What about having a _default.crt and _default.key in the certs volume, and a default SSL vhost using those files and always returning HTTP 503?

**Comment by rsynnest** [comment]
After beating my head against this for some hours, I found a fix for this 2 year old issue.
Here's what I've added to [line 201](https://github.com/jwilder/nginx-proxy/blob/226bfe158fc90b057cec727a7dd36b7a078cbe49/nginx.tmpl#L201) of nginx.tmpl in order to return a 444 (no response) for all unknown URLs served via SSL.
`
# default ssl to prevent vhost leakage
server {
    listen 443 default_server;
    ssl on;
    ssl_session_tickets off;
    ssl_certificate /etc/nginx/certs/{{ (printf "%s.crt" $cert) }};
    ssl_certificate_key /etc/nginx/certs/{{ (printf "%s.key" $cert) }};
    return 444;
}   
`

This provides a default fallback for SSL connections when the URL has no defined vhost, and returns 444 (no response). I added my default SSL block at [line 201](https://github.com/jwilder/nginx-proxy/blob/226bfe158fc90b057cec727a7dd36b7a078cbe49/nginx.tmpl#L201) so I could use the `$cert` variable. You could alternatively create a default crt and key file, but since I don't have those I just went with the existing `$cert` variable. Since the site won't be served anyway, it doesn't matter what cert+key you use here as they will not be used, the only reason you have to specify them is because nginx complains if they're not defined.

[This post](https://www.itworld.com/article/2987967/data-center/why-your-nginx-server-is-responding-with-content-from-the-wrong-site.html) provides a bit of info on what is going on when Nginx tries to "help out" by serving the best available site. The problem as Jas2Ma mentioned is the lack of a default SSL block to catch invalid vhosts. `nginx.tmpl` it's too dynamic and complex for me to really understand what's going on, but after generating the conf you can shell into the container and see that there is no 443 default block, only one for 80 (which returns a 503).

**Comment by rsynnest** [comment]
The nginx.tmpl has a default.crt and default.key but as you mentioned there is still no default SSL block to catch invalid SSL vhosts.
kamermans has a block in [this comment](https://github.com/jwilder/nginx-proxy/issues/950#issuecomment-337997133) which you can place as your first server block in nginx.tmpl.
Note his hardcoded crt+key domain. You can use any valid crt+key file here, since the site will not be served anyway, but nginx will not serve the block if those files are invalid.
Would make sense to add a invalid.crt and invalid.key and add the default SSL block to the default nginx.tmpl, I can think of no reason not to have this, and it is a headache to troubleshoot.

**Comment by buchdag** [comment]
This was fixed in #2186
