### ISSUE TITLE
ENABLE_IPV6=true does nothing

### ISSUE THREAD

**Issue by sandorvasas** [nginx-proxy/nginx-proxy#1453]
Or at least I think it does nothing. How can I verify IPv6 is actually enabled?
Executing `nginx -V` inside the container lists the configuration arguments, but `--with-ipv6` is not among them.

**Comment by adamu** [comment]
Works for me. If you can see the `listen [::]:80` entries in the `server` block, it's working.

I also thought it wasn't working originally, but it turned out IPV6 wasn't set up on the host itself.

**Comment by rodrigoaguilera** [comment]
I'm doing some tests and and as long the nginx-proxy port is exposed on an ipv6 address (`:::443->443/tcp` on the PORTS section of `docker ps`) the sites are served on ipv6. I tested with `curl -6`.
This makes me think that in current versions of nginx setting `listen [::]:80` in the conf is not necessary but `listen 80` is enough.
Therefore ENABLE_IPV6=true does nothing.
Can someone confirm?

**Comment by buchdag** [comment]
@rodrigoaguilera I think there is a confusion between what the Docker userland proxy does by default on IPv6 capable hosts and the nginx process actually listening to IPv6 inside the container.

`ENABLE_IPV6` does what is expected (making the container listening on IPv6), this can be verified with `lsof` and `curl -6` from inside the container.

Without `ENABLE_IPV6=true`:
```console
root@24f3aa659e00:/app# lsof -i
COMMAND PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
nginx    15 root    6u  IPv4 117056      0t0  TCP *:80 (LISTEN)
nginx    15 root   29u  IPv4 115299      0t0  TCP *:443 (LISTEN)
root@24f3aa659e00:/app# curl -I -v -6 http://localhost             
*   Trying [::1]:80...
* connect to ::1 port 80 failed: Connection refused
* Failed to connect to localhost port 80 after 0 ms: Couldn't connect to server
* Closing connection 0
curl: (7) Failed to connect to localhost port 80 after 0 ms: Couldn't connect to server
```
With `ENABLE_IPV6=true`:
```console
root@dbc89d349747:/app# lsof -i
COMMAND PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
nginx    17 root    6u  IPv4 111386      0t0  TCP *:80 (LISTEN)
nginx    17 root   29u  IPv6 114921      0t0  TCP *:80 (LISTEN)
nginx    17 root   30u  IPv4 114922      0t0  TCP *:443 (LISTEN)
nginx    17 root   31u  IPv6 114923      0t0  TCP *:443 (LISTEN)
root@dbc89d349747:/app# curl -I -v -6 http://localhost
*   Trying [::1]:80...
* Connected to localhost (::1) port 80 (#0)
> GET /basic_status HTTP/1.1
> Host: localhost
> User-Agent: curl/7.88.1
> Accept: */*
> 
[...]
```

Not having `ENABLE_IPV6` does not necessarily translate into _"the container can't be reached with `curl -6` from the host / the outside"_ because of the aforementioned Docker userland proxy.

What was the original intended use of `ENABLE_IPV6` (because I agree that it sound like it should enable or disable more than that), well that's another question 🤷
