### ISSUE TITLE
Allow self-signed SSL certificate without returning HTTP 500

### ISSUE THREAD

**Issue by cuzzo333** [nginx-proxy/nginx-proxy#1454]
For one my use cases I am attempting to use a self-signed SSL certificate.  From reading the README I understand that in using a self-signed cert, attempting to load my site using HTTPS will throw an http 500 error.  Is there a way to change this behavior so that the site will still load even when using a self-signed cert?

Also I saw that if we have a question to go to https://groups.google.com/forum/#!forum/nginx-proxy but I am unable to access this group or it seems to no longer exist.

**Comment by frankyrumple** [comment]
I adjusted the nginx.tmpl file a bit.  About line 240.
{{/* Use the cert specified on the container or fallback to the best vhost match */}}
{{/* $cert := (coalesce $certName $vhostCert) --- RULE CHANGE - use vhost first if it is present */}}
{{ $cert := (coalesce (or $vhostCert $certName) "") }}

This will pull the vhost first if matching, and then the cert name if present.  Otherwise, you end up with 500 if you don't explicitly set the CERT_NAME for the container (which is a pain if you want letsencrypt to kick in).  W this chance, I can use letsencrypt (vhost cert file exists) or fallback to default self signed cert.  My code is at: https://github.com/operepo/ope/tree/master/docker_build_files/ope-gateway

**Comment by KetchupBomb** [comment]
Expanding on @frankyrumple's response:
> This will pull the vhost first if matching, and then the cert name if present. Otherwise, you end up with 500 if you don't **explicitly set the CERT_NAME for the container** (which is a pain if you want letsencrypt to kick in). W this chance, I can use letsencrypt (vhost cert file exists) or fallback to default self signed cert. My code is at: https://github.com/operepo/ope/tree/master/docker_build_files/ope-gateway

If you set `CERT_NAME: default` on your containers, then they'll load using the default self-signed cert generated with nginx.

---

I, too, thought it would be sensible behavior to fallback to the default cert when there are no user-added certs, but after thinking about it for a bit I'm not so sure. The default cert will be invalid, both because of:
* being self-signed, and
* not supporting the common name (CN) subject alternative name(s) (SAN) of the container(s) created

Perhaps a better approach is to also explicitly state that we're willing to fallback to the default cert? But this, I believe, can be done in the [proxy-wide config](https://github.com/nginx-proxy/nginx-proxy#proxy-wide). It might be helpful to users like @cuzzo333 and myself, who expect this fallback to occur, to expose such a proxy-wide configuration as an environment variable on the `nginx-proxy` container itself.

**Comment by buchdag** [comment]
Trusting  the default certificate has been made possible (and the default behaviour) in #2535

There should not be any notion of self signed / not self signed in nginx-proxy: to the proxy a certificate is a certificate, the fact that it is valid or not is the user's concern, since it the user who's providing those certificates to the proxy.
