### ISSUE TITLE
DHPARAM_GENERATION env var ignored with false value

### ISSUE THREAD

**Issue by Silur** [nginx-proxy/nginx-proxy#1512]
## Issue
setting the `DHPARAM_GENERATION ` env var does not work as documented, it's either interpreted as a number or `true` but when given `false` you get `Can't parse "false" as a number`
seems like https://github.com/nginx-proxy/nginx-proxy/blob/master/generate-dhparam.sh#L29 regex doesn't match?

## steps to reproduce
`docker run -it --rm -e DHPARAM_GENERATION=false ...`
after startup it outputs `Can't parse "false" as a number`

running with image: `fcb5a96e19c1`

**Comment by SteveHespelt** [comment]
The issue is the passing of the 2 arguments to the /app/generate-dhparams.sh script.
If DHPARAM_BITS is not set, the value of $DHPARAM_GENERATION is used within the generate-dhparams.sh script as $1 so DHPARAM_BITS := false.
So the resulting statement becomes _openssl dhparam -dsaparam -out /tmp/z.tmp false_  (I changed the -out path), and the resulting error message is exactly as reported, & that I see as well.
Solution:  put " " around each argument, preserving the order as intended.
