### ISSUE TITLE
Docker nginx-proxy - handling  www 

### ISSUE THREAD

**Issue by MartinHarran** [nginx-proxy/nginx-proxy#1564]
I am using jwilder/nginx-proxy with jrcs/letsencrypt-nginx-proxy-companion. This script works perfectly inside docker-compose:
```  myweb:
    image: myimage:latest
    ports:
      - "8081:80"
    container_name: myweb
    networks:
      - "mynet"  
    environment:
      VIRTUAL_HOST: mydomain.com
      LETSENCRYPT_HOST: mydomain.com
      LETSENCRYPT_EMAIL: web@mydomain.com
```

How do I handle www.mydomain,com? I have tried VIRTUAL_HOST: mydomain.com,www.mydomain.com - tried separated with a comma and with a space - with and without www.mydomain.com added onto LETSENCRYPT_HOST

I have also created a CNAME record in my DNS pointing www.mydomain.com to mydomain.com,

________________________________________________________________

Footnote: on the template for creating a new issue, it says "If you have a question, DO NOT SUBMIT a new issue.  Please ask the question on the Q&A Group: https://groups.google.com/forum/#!forum/nginx-proxy" but that Google groups link doesn't seem to be working

**Comment by jacoblyw** [comment]
Hello,

You need to do put your desired virtual hostnames all together separated by commas (no spaces). Don't forget the dashes when you have a section with multiple values (like environment). I don't know if the YAML format requires the single quotes, but it works for me!

Like this:

    image: myimage:latest
    ports:
      - "8081:80"
    container_name: myweb
    networks:
      - "mynet"  
    environment:
      - VIRTUAL_HOST: mydomain.com
      - 'VIRTUAL_HOST=mydomain.com,www.mydomain.com,www2.mydomain.com'
      - LETSENCRYPT_HOST: mydomain.com
      - LETSENCRYPT_EMAIL: web@mydomain.com`

Good luck!

**Comment by MartinHarran** [comment]
Sorry, that's not what I meant - I want to redirect www.domain1 to domain1, www.domain2 to domain2, etc.

I can likely do it by creating a redirect container for each site but wonder is that really necessary.

**Comment by jacoblyw** [comment]
Note: I edited out `- VIRTUAL_HOST: mydomain.com` which I forgot to delete in my example above [sorry for any confusion].

The nginx-proxy is just that (a proxy): it's at the receiving end of incoming requests, connecting those requests to each container according to the VIRTUAL_HOST environment set on each container.

If you have a need to, you can run a different container for domain1 and another for domain2 (nginx-proxy doesn't care), or both can be set to go to your *myweb* container (as in my example).

Once the traffic gets to the destination container, that destination container needs to know what to do with that incoming traffic (to serve up one website for domain1 or another for domain2), but that depends on exactly what server software you have installed on that container.

The receiving container receives the traffic with the original requested domain--the proxy isn't doing redirection. If you need to do redirection from one domain to another (receiving traffic to domain1 but passing it to domain2) , you'll have to do that with a [Nginx redirection](https://stackoverflow.com/questions/6045020/how-to-redirect-to-a-different-domain-using-nginx) in the nginx-proxy configuration files.

This probably can be done modifying the nginx.tmpl to pull redirection values from another environment variable, but I haven't gotten the hang of GO in order to write the neccesary changes.

**Comment by MartinHarran** [comment]
Ok, that's fine, thx, It is a useful little utility despite that.
