### ISSUE TITLE
upstream prematurely closed connection while reading response header from upstream

### ISSUE THREAD

**Issue by educob** [nginx-proxy/nginx-proxy#1587]
Hi.

If the backend method takes several seconds I get a 502 error:

`upstream prematurely closed connection while reading response header from upstream, client: xx.yy.zz.aa, server: testnet.yyy.com, request: "POST /graphql HTTP/2.0", upstream: "http://pp.qq.yy.zz:4001/graphql", host: "testnet.yyy.com", referrer: "https://yyy.com/"`

What should I change?

Thanks.

**Comment by buchdag** [comment]
Hi. This error seems to indicate that the issue comes from your proxied app (`upstream prematurely closed connection`), not from the reverse proxy.

**Comment by educob** [comment]
Hi. Thanks for answering.

I have narrowed in the error. If my method in graphql takes 5 seconds the call fails in this way.
If the methods takes 4 or less seconds the call runs ok.

What can I do?

Thanks.

**Comment by b0s-at-works** [comment]
>upstream prematurely closed connection while reading response header from upstream, client: xx.yy.zz.aa, server: testnet.yyy.com, request: "POST /graphql **HTTP/2.0"**, upstream: "http://pp.qq.yy.zz:4001/graphql", host: "testnet.yyy.com", referrer: "https://yyy.com/"

Hi @educob, @buchdag and @jwilder! I can really be mistaken, but can you try to make an experiment of disabling this _http2_? It is turnes on, when you using ssl/https connection with certs, because _http2_ hardcoded in _[nginx.tmpl](https://github.com/nginx-proxy/nginx-proxy/blob/main/nginx.tmpl#L159):159_ and other few lines. In my case I have two days spent just trying to find what was the reason for (0 bytes body + no response code + no response headers) responses which was visible in browsers developers panels [Firefox, Chrome] literally as I described it it's a combo (0 bytes body + no response code + no response headers) when _HTTP/2_ is turned on in nginx configuration.

According to latest versions nginx [changes list](https://nginx.org/en/CHANGES), nginx author met diffirent kind of problems with _HTTP/2_ integration with SSL encryption (of course if I'm getting it rightly).
Also I tried to configure latest 1.19.(8 or 9 can't remember) nginx, I mean official nginx docker image, and this issue definitely happening with _http2_ parameter turned on even on clear 1.19.8-9 configuration just with ssl and http2 turned on.
There can be a huge chance that I doesn't set some http2 related configuration parameters which will fix issue, but they doesn't specified in nginx-proxy configuration too and also nginx author created few configuration settings according to nginx [changes log](https://nginx.org/en/CHANGES), which may be can be used to resolve this issue, but I 

Mean while dear @buchdag and @jwilder, I offer to add very needed (from my point and from my case) ability to manage _http/2_ with some environment variable switch, and allowing to downgrade to http 1, or to upgrade to http/2 from default http1 (it's up to you to decide), because, again, http2 hardcoded in nginx.tmpl and no way to manage it simply. You have to download nginx.tml from container (docker cp containerid:/app/nginx.tml) or from this git's repository's root and manually add it to vloumes.

With great respect!

**Comment by educob** [comment]
Hi. 
Thanks for your comment.

I copied nginx.tmpl file and added a volumes entry in docker-compose.yml
`- /home/ubuntu/ssl/nginx.tmpl:/app/nginx.tmpl

`In the file I moddified http2 -> http1. Not sure if this is what I had to do.

but when I recreated the containers the server is down. I get `This site can’t be reached`

What should I do?

Thanks.

**Comment by b0s-at-works** [comment]
@educob , try to remove, not add http1, but to remove http1/http1.1/http2. I mean just leave this line and other lines of listen directive/parameter without http[1,2];

change like this from:
	listen [::]:{{ $external_https_port }} ssl http2;
to:
	listen [::]:{{ $external_https_port }} ssl;

And do that for other lines with listen where http2 specified

**Comment by educob** [comment]
I found the error. My fault completely.

The sample code I pasted for the apollo server initialization had a 5 seconds timeout.
