### ISSUE TITLE
Wildcard certificates should only work one level deep

### ISSUE THREAD

**Issue by DonDebonair** [nginx-proxy/nginx-proxy#176]
Wildcard certificates are usually only valid "one level deep", so for example:

`*.example.com` works for `foo.example.com`, `bar.example.com`, but not for `fizz.buzz.example.com`.

Currently, nginx-proxy will pick up any certificate available, as long as there is a matching substring at the end. This means that a certificate called `example.com`, will also match `fizz.buzz.example.com`.
I think the offending line is this: https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L78

**Comment by chaos95** [comment]
+1. This has bitten me a couple of times now, when I've had sub-subdomains automatically redirect to HTTPS and immediately fail out because the automatically-selected certificate is invalid. My workaround was to set the CERT_NAME environment variable on the container in question to "" (empty string) to bypass the template logic which selects HTTPS over HTTP.

Obviously would like a solution that doesn't require a workaround though! :)

**Comment by tkw1536** [comment]
This is still an issue although the line numbers in `nginx.tmpl` have changed. 
Source line at the time the issue was created: https://github.com/nginx-proxy/nginx-proxy/blob/d74a4146c82e14664bf7da80260b6e3a01be8276/nginx.tmpl#L78
