### ISSUE TITLE
Latest build cannot find upstream ip addresses

### ISSUE THREAD

**Issue by seanjdunn85** [nginx-proxy/nginx-proxy#1870]
My latest build got the following /etc/nginx/conf.d/default.conf (no upstream IP address)

```nginx
upstream elasticsearch.snitcher.test {

}
server {
        server_name elasticsearch.snitcher.test;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://elasticsearch.snitcher.test;
        }
}
```

Downgrading to 0.9 got a working config:

```nginx
upstream elasticsearch.snitcher.test {
        ## Can be connected with "snitcher_main" network
        # elasticsearch
        server 172.18.0.2:9200;
}
server {
        server_name elasticsearch.snitcher.test;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://elasticsearch.snitcher.test;
        }
}

```
LMK if you need more details

**Comment by buchdag** [comment]
Hi.

Could you post the details of your nginx-proxy and elasticsearch containers configuration (full compose files for example) + the result of `docker inspect` for both containers ?

This issue is usually either caused by the docker-gen process being unable to acquire its own container ID or the proxied containers not having at least one Docker network in common with the nginx-proxy container (or docker-gen not being able to tell that's actually the case).

We did not change anything related to this since `0.9.3` (which is the same as `0.9`), so that's strange.

**Comment by jontro** [comment]
Probably related to https://github.com/nginx-proxy/nginx-proxy/issues/1869

**Comment by buchdag** [comment]
No answer from issue creator.
