### ISSUE TITLE
proxy_pass for subdirectories

### ISSUE THREAD

**Issue by WillBeebe** [nginx-proxy/nginx-proxy#190]
Hi, I have to say I love this Dockerfile! I got it working with

```
-e VIRTUAL_HOST="localhost"
```

However, I have three rails apps that live in the same domain. 

```
domain.com
domain.com/one-app
domain.com/another-app
```

I'd love to use this tool to proxy_pass to these different rails apps. When I try 

```
-e VIRTUAL_HOST="localhost/one-app"
```

I get a warning.

```
2015/06/29 20:15:50 [warn] 14#14: server name "localhost/about" has suspicious symbols in /etc/nginx/conf.d/default.conf:126
```

If there a way to do what I'm describing with this? Mainly I'd like all traffic to `domain.com/one-app` to be routed to one of my containers.

**Comment by WillBeebe** [comment]
I see there's a pull request out for something like this:

https://github.com/appropriate/nginx-proxy/tree/multiple-paths

It looks like a nice feature :-)

**Comment by md5** [comment]
This has been discussed in issue #47, so I think that's the best place for further discussion.

As you found, I did create a branch to start tackling the path-based dispatch issue, which at one point was opened as PR #54, but I closed it because the functionality is not complete.

The remaining open issues as I recall are:

1. Sort the available `VIRTUAL_PATH` values for a `VIRTUAL_HOST` to ensure that dispatch will work in cases of prefix overlap (e.g. a container with `VIRTUAL_PATH=/api` alongside a container with `VIRTUAL_PATH=/api/v1`).
2. Ensure that a `503` status code is still returned if `VIRTUAL_PATH` is being used and there is no container mapped to `VIRTUAL_PATH=/`.

In the current state of my branch, the behavior for the first item is essentially random, though I think it's probably stable without the lifecycle of a single Docker daemon process. For the second item, a default Nginx index page is being served with status code `200`. I don't think that either of those behaviors is suitable for a merge.

**Comment by buchdag** [comment]
This features has been added to the `dev` branch with #1607 

It's available now on the `dev` images `nginxproxy/nginx-proxy:dev` and `nginxproxy/nginx-proxy:dev-alpine`. Testing and feedback are welcome, the docs for the feature is [here](https://github.com/nginx-proxy/nginx-proxy/tree/dev#path-based-routing) and there is [another PR](https://github.com/nginx-proxy/nginx-proxy/pull/1699) opened for additional improvements and comments.
