### ISSUE TITLE
SSL_POLICY=Mozilla-Modern got worse results on SSLLabs SSLtest than intermediate

### ISSUE THREAD

**Issue by Nimrod-666** [nginx-proxy/nginx-proxy#2308]
Hi, i'm using the latest nginxproxy/nginx-proxy:alpine image image and i got the issue, that when i set SSL_POLICY=Mozilla-Modern, i got worse results on the [ssllabs ssltest ](https://www.ssllabs.com/ssltest/) than on the default intermediate one. (A+ on intermediate, B on modern). It seems that the modern profile enables some legacy settings that are not enabled by the intermediate on, which would be strange.

How to reproduce:

- Make a https://www.ssllabs.com/ssltest/ test without the SSL_POLICY parameter set
- Set the "SSL_POLICY=Mozilla-Modern" envvar on the container and rebuild
- Repeat the ssllabs test (You need to use the "clear cache" function of the test!)

**Comment by buchdag** [comment]
Test report for  [Mozilla-Intermediate](https://github.com/nginx-proxy/nginx-proxy/files/13621380/mozilla-intermediate.pdf) and [Mozilla-Modern](https://github.com/nginx-proxy/nginx-proxy/files/13621381/mozilla-modern.pdf) after the fix. As you can see Mozilla-Intermediate is still ranked A+ and Mozilla-Modern A, probably because explicitly not supporting TLSv1.2 prevents you from getting A+.
