### ISSUE TITLE
Interaction with dockerui: sub-path-api request cause no cookie issue

### ISSUE THREAD

**Issue by llitfkitfk** [nginx-proxy/nginx-proxy#372]
```
docker run -d -p 9001:9000 -v /var/run/docker.sock:/var/run/docker.sock dockerui/dockerui 
```

Request http://192.168.0.1:9001/dockerapi/containers/json?all=0, can get container info respose.

But when I using  

```
docker run -d -v /var/run/docker.sock:/var/run/docker.sock \
    -e VIRTUAL_HOST=dockerui.mydomain.com \
    -e VIRTUAL_PORT=9000 \ 
    dockerui/dockerui 
```

Request http://dockerui.mydomain.com/dockerapi/containers/json?all=0, I got `persistent connection closed` in the dockerui container logs

**Comment by dizlexik** [comment]
I'm experiencing the same issue while attempting to expose dockerui with [nginx proxy](https://github.com/jwilder/nginx-proxy). I can hit the site and nearly everything loads except I receive 500 errors on the ajax calls and have a `persistent connection closed` line in my dockerui container logs for each ajax request attempt.

**Comment by schamp** [comment]
If this is still a problem, see: https://github.com/kevana/ui-for-docker/issues/204

I had to read between the lines a bit, but I ended up adding the following volume:
 `-v /home/<user>/vhost.d:/etc/nginx/vhost.d`

and then putting the a file containing:
`proxy_set_header Connection $http_connection` in what for you would be the equivalent of `vhost.d/dockerui.mydomain.com_location`

After this and a `docker exec nginx-proxy sudo service nginx restart, I was good to go

(though because I had configured a default host of my own, I also had to also `docker exec nginx-proxy sudo rm /etc/nginx/sites-enabled/default` to get rid of `nginx: [emerg] a duplicate default sever for 0.0.0.0:80 in /etc/nginx/sites-enabled/default:17` but I believe that's a separate problem)

**Comment by tkw1536** [comment]
Seems resolved, as per last comment. Closing
