### ISSUE TITLE
Bad endpoint: stat /tmp/docker.sock: permission denied

### ISSUE THREAD

**Issue by nicohvi** [nginx-proxy/nginx-proxy#40]
`docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock jwilder/nginx-proxy` 

yields the following error (from `docker logs`)

```
forego     | starting nginx.1 on port 5000
forego     | starting dockergen.1 on port 5100
dockergen.1 | 2014/10/03 20:34:10 Bad endpoint: stat /tmp/docker.sock: permission denied
forego     | starting dockergen.1 on port 5100
forego     | sending SIGTERM to dockerge
```

**Comment by sigelinde** [comment]
I found the option that works well on my environment: `--security-opt=label:type:docker_t`
Does it work for you?

**Comment by rdavaillaud** [comment]
@sigelinde Yes, it pass the step, now I've got another problem, but it's not the same!
Thank you

**Comment by gabeos** [comment]
I've gotten this to work by adding a module to the SELinux policy.

My current module is here:
https://gist.github.com/2205f8e36dfa3d2f5b63

compile and add to policy with:
```
# checkmodule -M -m -o docker_socketaccess.mod docker_socketaccess.te
# semodule_package -o docker_socketaccess.pp -m docker_socketaccess.mod
# semodule -i docker_socketaccess.pp 
```
Should work, but if not, you can check why by running:
```
# grep docker /var/log/audit/audit.log | audit2why
```
and you can generate a new module to insert that will allow the currently denied behavior with:
```
# grep docker /var/log/audit/audit.log | audit2allow -M <module_name>
# semodule -i <module_name>.pp
```

**Comment by Mr00Anderson** [comment]
I have also had this issue. After much searching I found out that my username space was enabled and preventing my container from having docker.sock access. ```--userns=host``` resolved my issue.

**Comment by akiross** [comment]
> `--security-opt=label:type:docker_t`

This is working for me as well, thanks! Maybe it could be documented somewhere?

**Comment by cuzzo333** [comment]
Hoping to get some support on this issue.  In my environment we're looking to run nginx-proxy with a non-root user account.  I've cloned the nginx-proxy repository so that I could modify the dockerfile formy purposes (creating a non root user, chown'ing necessary directories, etc.)

One area I am still stuck on is permissions to /tmp/docker.sock.  I've attempted the various fixes already mentioned here but I believe my issue is slightly different in that I am attempting to run nginx-proxy with a non-root user.

Does anybody know if it's possible to modify permissions on /tmp/docker.sock for a non-root user?  I've attempted a few other things such as mounting the volume during my `docker run` command as a non-root user but still can't find a way around this.
