### ISSUE TITLE
Customize log_format

### ISSUE THREAD

**Issue by gauravarora** [nginx-proxy/nginx-proxy#564]
I wanted to customize the `log_format` but it seems I cannot in the current form. I wanted to send over a PR but I just wanted to run the implementation by you once @jwilder. 

I was planning of doing the implementation in the same fashion as `/etc/nginx/proxy.conf`. So I will use `/etc/nginx/log_format.conf` and include a default `log_format` if the file isn't present. Does that sound like a good solution?

**Comment by ulrith** [comment]
I tried to use custom log_format with the following steps:

1. Put my custom log_format "combined_plus" definition in .conf file in the conf.d folder which then mounted inside nginx-proxy.
2. Add access_log definition in vhost.d/domain.tld  file with the mount of vhost.d folder.

After that I've got an error:
```
unknown log format "combined_plus" in /etc/nginx/vhost.d/domain.tld:1
```

**Comment by ulrith** [comment]
@jwilder Sorry for the false bug report - the problem was on my side. I've named the .conf file which contains log_format directive 'okmeter.conf' so it was loaded after default.conf which is the reason of the error. After I renamed it to '00-okmeter.conf' everything works like a charm.

I suggest this issue to be closed - log_format can be customized without any problem.

**Comment by tkw1536** [comment]
Closing as per last comment
