### ISSUE TITLE
DES ciphers should be removed

### ISSUE THREAD

**Issue by hasufell** [nginx-proxy/nginx-proxy#586]
They are weak and https://tls.imirhil.fr/https gives a very bad grade for servers providing that cipher suite.

**Comment by kamermans** [comment]
I'm working on this in my `feature_ssl_improvements` branch off my fork.  I've removed the ciphers and pushed it to Docker hub as `kamermans/nginx-proxy:ssl_upgrade`.  Note that it also includes a 2048-bit `dhparam.pem` by default now.  I'll try to give it a spin with a real cert later tonight, but your confirmation would be helpful as well.

**Comment by tkw1536** [comment]
DES Ciphers have been removed since this issue was filed, closing,

See [the README](https://github.com/nginx-proxy/nginx-proxy#how-ssl-support-works) on how SSL profiles work and https://github.com/nginx-proxy/nginx-proxy/blob/c4ad18fecce35da83adcca334fffd00afd75dced/nginx.tmpl#L11-L50 for the concrete set of ciphers.
